---
- src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse

- src: https://github.com/wiqt8r/vector-role.git
  scm: git
  version: "v0.1.0"
  name: vector-role

- src: https://github.com/wiqt8r/lighthouse-role.git
  scm: git
  version: "v0.1.0"
  name: lighthouse-role
