---
- name: Install ClickHouse
  hosts: clickhouse
  roles:
    - role: clickhouse
  tags: [clickhouse]

- name: Install Vector
  hosts: vector
  roles:
    - role: vector-role
  tags: [vector]

- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - role: lighthouse-role
  tags: [lighthouse]
